### ISSUE TITLE
How accessible are you planning on making your webpage?

### ISSUE THREAD

**Issue by norman-kong** [ZaidaEMtzMo/how2fMRI#5]
I am not sure how advanced you want to make your resource, but in case you want to attract people who are new to the field, I believe that introductory resources describing what fMRI is will be of great value. 

For example: https://www.researchgate.net/publication/285245634_An_introduction_to_fMRI

I will send you any good resources that I find throughout the completion of my project. You may or may not want to include them in your list of resources.

**Comment by ZaidaEMtzMo** [comment]
I think that I want to include a small introduction for all of the different software and techniques, but also for neuroscience itself and how to use them. However, if I find good tutorials on the Internet, instead of duplicating them, I will just include the links.
